# Generated by Django 3.2.9 on 2022-03-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_social_youtube_profile_social_stackoverflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name']},
        ),
    ]
